### ISSUE TITLE
Complain about events that don't have final rounds

### ISSUE THREAD

**Issue by jfly** [cubing/wca-workbook-assistant#104]
This happened with Los Lomas 2014:

![2015-02-13_836x111_laptor](https://cloud.githubusercontent.com/assets/277474/6195257/182ebfb6-b381-11e4-8f70-4d48460792e0.png)

The wca upload scripts were able to detect and fix this, but they didn't fix the corresponding uploaded scrambles (an understandable oversight, since we only added scramble uploading recently).

**Comment by jazzthief81** [comment]
This is a duplicate of #68.
