### ISSUE TITLE
We don't handle corrupt zip files very well

### ISSUE THREAD

**Issue by jfly** [cubing/wca-workbook-assistant#110]
(I thought we already had an issue for this, but I could not find it. @jazzthief81, was there an issue for this already?)

Arash just ran into this issue. I'm pretty sure something bad happened while downloading the database export, and then he ended up in a state where the workbook assistant would barf while trying to parse the downloaded zip file, but not display any terribly obvious errors to him: https://groups.google.com/d/msg/wca-software/duXwRE8Opp0/dIKNm84wBwAJ.

**Comment by jazzthief81** [comment]
@jfly Work has already been done, see https://github.com/cubing/wca-workbook-assistant/issues/94

**Comment by jfly** [comment]
Ah, nevermind! The behavior when no export is downloaded is a bit weird, but there is a nice red message on the bottom of the window. Closing this issue.
